import * as path from "path";
import { IStyleGeneratorItem } from "../interfaces/style-generator";
import { IImage } from "../interfaces/image";
import { Orientation, Stylesheet } from "../utils/enum";
import { Options } from "../utils/options";
import { StringUtils } from "../utils/string";

export class StyleGeneratorHelpers {
    styleItem: IStyleGeneratorItem;
    resultText: string;

    constructor(styleItem: IStyleGeneratorItem) {
        this.styleItem = styleItem;

        this.resultText = "/*\n";
        this.resultText += "\tGenerated by Image Sprites (https://marketplace.visualstudio.com/items?itemName=gurayyarar.imagesprites)\n";
        this.resultText += "\tAuthor: Güray Yarar (https://github.com/gurayyarar)\n";
        this.resultText += "*/\n\n";
    }

    getStyleText(): string {
        if (this.styleItem.options.stylesheet === Stylesheet.Scss || this.styleItem.options.stylesheet === Stylesheet.Less) {
            return this.scssAndLess();
        } else {
            return this.css();
        }
    }

    private css(): string {
        // Background Image
        this.resultText += `.${this.styleItem.sprite_image} {\n`;
        this.resultText += "\tbackground-image: url('";
        if (this.styleItem.options.path_prefix !== "" && this.styleItem.options.path_prefix !== null) {
            this.resultText += this.styleItem.options.path_prefix;
        }
        this.resultText += `${this.styleItem.sprite_image}.sprite.${Options.getOptions().output}`;
        if (this.styleItem.options.enable_cache_busting) {
            this.resultText += `?v=${new StringUtils().getCacheBustingKey()}`;
        }
        this.resultText += "');\n";

        // Background Repeat
        this.resultText += "\tbackground-repeat: no-repeat;\n";

        // Custom Style(s)
        for (let key in this.styleItem.options.custom_styles) {
            this.resultText += `\t${key}: ${this.styleItem.options.custom_styles[key]};\n`;
        }

        this.resultText += "}\n\n";

        let coordinantY: number = 0, coordinantX: number = 0;
        this.styleItem.items.forEach((item: IImage, index: number) => {
            this.resultText += `.${this.styleItem.sprite_image}.${path.basename(item.file_path, path.extname(item.file_path))} {\n`;
            this.resultText += `\twidth: ${item.width}px;\n`;
            this.resultText += `\theight: ${item.height}px;\n`;

            if (this.styleItem.options.orientation === Orientation.Vertical) {
                coordinantY += this.styleItem.options.padding;
                this.resultText += `\tbackground-position: -${this.styleItem.options.padding}px -${coordinantY}px;\n`;
                coordinantY += item.height;
            } else {
                coordinantX += this.styleItem.options.padding;
                this.resultText += `\tbackground-position: -${coordinantX}px -${this.styleItem.options.padding}px;\n`;
                coordinantX += item.width;
            }

            this.resultText += "}\n";
        });
        return this.resultText;
    }

    private scssAndLess(): string {
        // Background Image
        this.resultText += `.${this.styleItem.sprite_image} {\n`;
        this.resultText += "\tbackground-image: url('";
        if (this.styleItem.options.path_prefix !== "" && this.styleItem.options.path_prefix !== null) {
            this.resultText += this.styleItem.options.path_prefix;
        }
        this.resultText += `${this.styleItem.sprite_image}.sprite.${Options.getOptions().output}`;
        if (this.styleItem.options.enable_cache_busting) {
            this.resultText += `?v=${new StringUtils().getCacheBustingKey()}`;
        }
        this.resultText += "');\n";

        // Background Repeat
        this.resultText += "\tbackground-repeat: no-repeat;\n";

        // Custom Style(s)
        for (let key in this.styleItem.options.custom_styles) {
            this.resultText += `\t${key}: ${this.styleItem.options.custom_styles[key]};\n`;
        }

        let coordinantY: number = 0, coordinantX: number = 0;
        this.styleItem.items.forEach((item: IImage, index: number) => {
            this.resultText += `\t&.${path.basename(item.file_path, path.extname(item.file_path))} {\n`;
            this.resultText += `\t\twidth: ${item.width}px;\n`;
            this.resultText += `\t\theight: ${item.height}px;\n`;

            if (this.styleItem.options.orientation === Orientation.Vertical) {
                coordinantY += this.styleItem.options.padding;
                this.resultText += `\t\tbackground-position: -${this.styleItem.options.padding}px -${coordinantY}px;\n`;
                coordinantY += item.height;
            } else {
                coordinantX += this.styleItem.options.padding;
                this.resultText += `\t\tbackground-position: -${coordinantX}px -${this.styleItem.options.padding}px;\n`;
                coordinantX += item.width;
            }

            this.resultText += "\t}\n";
        });

        this.resultText += "}";
        return this.resultText;
    }
}